### ISSUE TITLE
nod.ai SHARK 20230214.527: Dark theme not available in the exe release

### ISSUE THREAD

**Issue by m68k-fr** [nod-ai/SHARK#1016]
I built the release locally and the css is missing, this problem only occured in the exe release.
It's a relative path issue, similar to the problem encountered in https://github.com/nod-ai/SHARK/pull/1001/

After the tabbed interface was introduced, the css call is now done from the parent folder, leading to a path failure in the exe version.

It can easily be fix, by editing the shark_sd.spec:
Replace
`( 'web/ui/css/*', 'css' ),`
by
`( 'web/ui/css/*', 'ui/css' ),`

It's a quick and easy fix, but I don't recommend this.
I haven't taken the time to dig further, but I suspect it will reapper as soon as we load web resources from a different path.
More over it will make the web resources declarations in shark_sd.spec inconsistant.
In my opinion it would be preferabe to investigate more in `def resource_path(relative_path):`

**Comment by powderluv** [comment]
Thanks for the report. I pushed a temporary fix. We can discuss best way to fix it

**Comment by m68k-fr** [comment]
You're welcome.

**Comment by m68k-fr** [comment]
I just noticed the push , only the css path had to be modified, the logo was ok.
`( 'web/ui/logos/*', 'ui/logos' )`
