### ISSUE TITLE
Feature request: add default model argument

### ISSUE THREAD

**Issue by kirill-21** [nod-ai/SHARK#1046]
Can you please add an argument that allows to specify the default model so that it does not need to be changed on each stable diffusion launch?
![image](https://user-images.githubusercontent.com/63228361/219698864-05d4a6cd-145c-49bf-a722-a1729304e5cf.png)

**Comment by m68k-fr** [comment]
It's already available. Add --ckpt_loc with your default model and the Ui drop-down should initialize on it.

**Comment by kirill-21** [comment]
> It's already available. Add --ckpt_loc with your default model path+name and the Ui drop-down should initialize on it.

Thank you, that works
