### ISSUE TITLE
Closes after "Vulcan devices are available"

### ISSUE THREAD

**Issue by danbradford7** [nod-ai/SHARK#1127]
Not sure what's going on, I've deleted all my files and started fresh, but every time I try to load the latest stable release, it says:

shark_tank local cache is located at C:\Users\*ME*\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.

C:\Users\*ME*>

**Comment by powderluv** [comment]
What card are you on ? builds > 574 are currently broken for rdna2

**Comment by danbradford7** [comment]
6800XT. I figured out how to fix it, Apparently the old Nvidia drivers from my last card were causing issues. It works perfectly now

**Comment by PennyFranklin** [comment]
> 你在什么卡上？> 574 的内部版本目前已针对 RDNA2 损坏

so how about RDNA3? my video card is 7900xtx,and it's same problem

**Comment by powderluv** [comment]
Can you please start it from the powershell / cmd terminal and report what error you see ?
