### ISSUE TITLE
577 broken

### ISSUE THREAD

**Issue by GoZippy** [nod-ai/SHARK#1135]
573 to 577 broken on RX6700 for txt to img 

using --clear_all to reset or not - same issue

delete old vmfb and recompile - takes long time - then loading config seems to go through then no vmfb found so compiles again then the old registry lookup failed to get layer manifest file error... but it keeps going.. then runtime error registering modules

     File "iree\runtime\system_api.py", line 255, in add_vm_module
     File "iree\runtime\system_api.py", line 252, in add_vm_modules
RuntimeError: Error registering modules: D:\a\SHARK-Runtime\SHARK-Runtime\c\runtime\src\iree\hal\drivers\vulkan\native_executable.cc:157: UNKNOWN; VkResult=4294967283; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module.__init:2828 <eval_with_key>.41:134:18

**The odd thing I see is the drive letter - I am on drive E not D...**

**Comment by powderluv** [comment]
Thank you for the report. @yzhang93 is investigating it. It is broken on RDNA2 and lower devices but works on RDNA3

**Comment by yzhang93** [comment]
It is fixed now. Please try with our next release later today.

**Comment by GoZippy** [comment]
working now - please mark solved.
