### ISSUE TITLE
Can no longer one click run

### ISSUE THREAD

**Issue by Dnak-jb** [nod-ai/SHARK#1174]
I recently upgraded by GPU, and wanted to test to see the increase in speed in shark.  When I had my 5700xt, shark was a one click easy installation that worked the first time.  But once I upgraded and tried used newer versions, it didn't seem to last.  I tried a few things, like clearing the cache folders in vukan and huggingface, starting with program with the "clear" argument, as well as pointing the program to the shark tank folder.  I also tried deleting the files created in the users/temp folder to attempt to redownload them.  I also tried multiple new versions from 591 to 568.  I even went back as far as 445 where it was last working for me but got a slightly different error output that I will put second.

None of these seemed to effect the outcome.

4930k @ 4.5ghz
24gb ddr3 @ 1866
7900xtx
running off of system SSD
windows 10 22H2 - build 19045.2604 - Windows Feature Experience Pack 120.2212.4190.0

*The program told me to post this here!*

**BUILD 568**

`shark_tank local cache is located at C:\Users\sk8er\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Using tuned models for Linaqruf/anything-v3.0/fp16/vulkan://00000000-0300-0000-0000-000000000000.
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 7.79kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 36.1kB/s]
loading existing vmfb from: C:\Users\sk8er\Desktop\shark\euler_scale_model_input_fp16.vmfb
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 7.27kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 36.4kB/s]
loading existing vmfb from: C:\Users\sk8er\Desktop\shark\euler_step_fp16.vmfb
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 4.73kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 36.3kB/s]
loading existing vmfb from: C:\Users\sk8er\Desktop\shark\av3_vae_19dec_fp16_tuned.vmfb
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 4.19kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 36.6kB/s]
loading existing vmfb from: C:\Users\sk8er\Desktop\shark\av3_clip_19dec_fp32.vmfb
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 6.28kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 53.2kB/s]
No vmfb found. Compiling and saving to C:\Users\sk8er\Desktop\shark\av3_unet_19dec_fp16_tuned.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
download pipeline failed, falling back to import_mlir
Inferring base model configuration.
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Traceback (most recent call last):
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 378, in from_pretrained
  File "apps\stable_diffusion\src\models\opt_params.py", line 54, in get_unet
  File "apps\stable_diffusion\src\utils\utils.py", line 82, in get_shark_model
  File "apps\stable_diffusion\src\utils\utils.py", line 53, in _compile_module
  File "shark\shark_inference.py", line 188, in save_module
  File "shark\iree_utils\compile_utils.py", line 342, in export_iree_module_to_vmfb
  File "shark\iree_utils\compile_utils.py", line 279, in compile_module_to_flatbuffer
  File "iree\compiler\tools\core.py", line 280, in compile_str
  File "iree\compiler\tools\binaries.py", line 198, in invoke_immediate
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
LLVM ERROR: out of memory
Allocation failed
Please report issues to https://github.com/openxla/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\Users\\sk8er\\AppData\\Local\\Temp\\_MEI108122\\iree\\compiler\\tools\\..\\_mlir_libs\\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvmcpu-embedded-linker-path=C:\\Users\\sk8er\\AppData\\Local\\Temp\\_MEI108122\\iree\\compiler\\tools\\..\\_mlir_libs\\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host "--iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control, VK_NV_cooperative_matrix], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit, cooperativeMatrixPropertiesNV = [#vk.coop_matrix_props<mSize = 16, nSize = 16, kSize = 16, aType = f16, bType = f16, cType = f16, resultType = f16, scope = #vk.scope<Subgroup>>] >>" --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-windows
Exception Code: 0x80000003
0x00007FF9EC0A72E5, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3CD72E5 byte(s), mlirTypeIDHashValue() + 0x391C7E5 byte(s)
0x00007FFA76DC1881, C:\WINDOWS\System32\ucrtbase.dll(0x00007FFA76D50000) + 0x71881 byte(s), raise() + 0x1E1 byte(s)
0x00007FFA76DC2851, C:\WINDOWS\System32\ucrtbase.dll(0x00007FFA76D50000) + 0x72851 byte(s), abort() + 0x31 byte(s)
0x00007FF9EC01AA85, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C4AA85 byte(s), mlirTypeIDHashValue() + 0x388FF85 byte(s)
0x00007FF9EC005C90, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C35C90 byte(s), mlirTypeIDHashValue() + 0x387B190 byte(s)
0x00007FF9EC0358C8, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C658C8 byte(s), mlirTypeIDHashValue() + 0x38AADC8 byte(s)
0x00007FF9EC01BB08, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C4BB08 byte(s), mlirTypeIDHashValue() + 0x3891008 byte(s)
0x00007FF9EC01B7CD, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C4B7CD byte(s), mlirTypeIDHashValue() + 0x3890CCD byte(s)
0x00007FF9EC003576, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C33576 byte(s), mlirTypeIDHashValue() + 0x3878A76 byte(s)
0x00007FF9EC003516, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x3C33516 byte(s), mlirTypeIDHashValue() + 0x3878A16 byte(s)
0x00007FF9E846DDC6, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x9DDC6 byte(s), ireeCompilerSourceOpenFile() + 0xB6 byte(s)
0x00007FF9E845FA39, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9E83D0000) + 0x8FA39 byte(s), mlirBlockArgumentGetArgNumber() + 0x1D69 byte(s)
0x00007FF7586A11FC, C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\_mlir_libs\iree-compile.exe(0x00007FF7586A0000) + 0x11FC byte(s)
0x00007FFA77997614, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFA77980000) + 0x17614 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FFA790426A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFA78FF0000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)

Invoked with:
 iree-compile.exe C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvmcpu-embedded-linker-path=C:\Users\sk8er\AppData\Local\Temp\_MEI108122\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvmcpu-target-cpu-features=host --iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control, VK_NV_cooperative_matrix], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit, cooperativeMatrixPropertiesNV = [#vk.coop_matrix_props<mSize = 16, nSize = 16, kSize = 16, aType = f16, bType = f16, cType = f16, resultType = f16, scope = #vk.scope<Subgroup>>] >> --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-windows

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1032, in process_api
  File "gradio\blocks.py", line 858, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 448, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 122, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 410, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 541, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues`

**BUILD 445**

`torchvision\io\image.py:13: UserWarning: Failed to load image Python extension:
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001F029AA5240>.
  warnings.warn(
torch\_jit_internal.py:839: UserWarning: Unable to retrieve source for @torch.jit._overload function: <function _DenseLayer.forward at 0x000001F029AA7520>.
  warnings.warn(
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 7900 XTX. Using target triple rdna3-7900-windows.
Using tuned models for stablediffusion/fp16 and rdna3 card.
shark_tank local cache is located at C:\Users\sk8er\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 50.5kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 53.2kB/s]
No vmfb found. Compiling and saving to C:\Users\sk8er\Desktop\old shark\euler_scale_model_input_fp16_vulkan-00000000-0300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
Saved vmfb in C:\Users\sk8er\Desktop\old shark\euler_scale_model_input_fp16_vulkan-00000000-0300-0000-0000-000000000000.vmfb.
Using cached models from C:\Users\sk8er\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 35.7kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 36.7kB/s]
No vmfb found. Compiling and saving to C:\Users\sk8er\Desktop\old shark\euler_step_fp16_vulkan-00000000-0300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
Saved vmfb in C:\Users\sk8er\Desktop\old shark\euler_step_fp16_vulkan-00000000-0300-0000-0000-000000000000.vmfb.
Downloading artifacts for model vae2base_19dec_fp16_tuned...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [00:00<00:00, 1.22kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.50M/1.50M [00:00<00:00, 5.82MB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 3.74kB/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.3k/32.3k [00:00<00:00, 234kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 3.20kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 189M/189M [00:10<00:00, 18.9MB/s]
No vmfb found. Compiling and saving to C:\Users\sk8er\Desktop\old shark\vae2base_19dec_fp16_tuned_vulkan-00000000-0300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
Saved vmfb in C:\Users\sk8er\Desktop\old shark\vae2base_19dec_fp16_tuned_vulkan-00000000-0300-0000-0000-000000000000.vmfb.
Downloading artifacts for model unet_19dec_v2p1base_fp16_64_tuned...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 156/156 [00:00<00:00, 1.11kB/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32.3k/32.3k [00:00<00:00, 191kB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 5.12kB/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 289k/289k [00:00<00:00, 1.58MB/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.91G/3.91G [04:48<00:00, 14.5MB/s]
No vmfb found. Compiling and saving to C:\Users\sk8er\Desktop\old shark\unet_19dec_v2p1base_fp16_64_tuned_vulkan-00000000-0300-0000-0000-000000000000.vmfb
Using target triple -iree-vulkan-target-triple=rdna3-7900-windows from command line args
Traceback (most recent call last):
  File "gradio\routes.py", line 322, in run_predict
  File "gradio\blocks.py", line 1015, in process_api
  File "gradio\blocks.py", line 833, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "models\stable_diffusion\main.py", line 143, in stable_diff_inf
  File "models\stable_diffusion\cache_objects.py", line 107, in set_models
  File "models\stable_diffusion\opt_params.py", line 72, in get_unet
  File "models\stable_diffusion\utils.py", line 58, in get_shark_model
  File "models\stable_diffusion\utils.py", line 33, in _compile_module
  File "shark\shark_inference.py", line 186, in save_module
  File "shark\iree_utils\compile_utils.py", line 323, in export_iree_module_to_vmfb
  File "shark\iree_utils\compile_utils.py", line 270, in compile_module_to_flatbuffer
  File "iree\compiler\tools\core.py", line 278, in compile_str
  File "iree\compiler\tools\binaries.py", line 196, in invoke_immediate
iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile.exe
Diagnostics:
LLVM ERROR: out of memory
Allocation failed
Please report issues to https://github.com/iree-org/iree/issues and include the crash backtrace.
Stack dump:
0.      Program arguments: C:\\Users\\sk8er\\AppData\\Local\\Temp\\_MEI83882\\iree\\compiler\\tools\\..\\_mlir_libs\\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=C:\\Users\\sk8er\\AppData\\Local\\Temp\\_MEI83882\\iree\\compiler\\tools\\..\\_mlir_libs\\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host "--iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control, VK_NV_cooperative_matrix], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit, cooperativeMatrixPropertiesNV = [#vk.coop_matrix_props<mSize = 16, nSize = 16, kSize = 16, aType = f16, bType = f16, cType = f16, resultType = f16, scope = #vk.scope<Subgroup>>] >>" --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-windows
Exception Code: 0x80000003
0x00007FF9DCB28245, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3B18245 byte(s), mlirTypeIDHashValue() + 0x3768C35 byte(s)
0x00007FFA76DC1881, C:\WINDOWS\System32\ucrtbase.dll(0x00007FFA76D50000) + 0x71881 byte(s), raise() + 0x1E1 byte(s)
0x00007FFA76DC2851, C:\WINDOWS\System32\ucrtbase.dll(0x00007FFA76D50000) + 0x72851 byte(s), abort() + 0x31 byte(s)
0x00007FF9DCA9D6C5, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A8D6C5 byte(s), mlirTypeIDHashValue() + 0x36DE0B5 byte(s)
0x00007FF9DCA88920, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A78920 byte(s), mlirTypeIDHashValue() + 0x36C9310 byte(s)
0x00007FF9DCAB84E8, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3AA84E8 byte(s), mlirTypeIDHashValue() + 0x36F8ED8 byte(s)
0x00007FF9DCA9E748, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A8E748 byte(s), mlirTypeIDHashValue() + 0x36DF138 byte(s)
0x00007FF9DCA9E40D, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A8E40D byte(s), mlirTypeIDHashValue() + 0x36DEDFD byte(s)
0x00007FF9DCA85A26, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A75A26 byte(s), mlirTypeIDHashValue() + 0x36C6416 byte(s)
0x00007FF9DCA859C6, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x3A759C6 byte(s), mlirTypeIDHashValue() + 0x36C63B6 byte(s)
0x00007FF9D90A8D36, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x98D36 byte(s), ireeCompilerSourceOpenFile() + 0xB6 byte(s)
0x00007FF9D909A9E9, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\IREECompiler.dll(0x00007FF9D9010000) + 0x8A9E9 byte(s), mlirBlockArgumentGetArgNumber() + 0x1D69 byte(s)
0x00007FF7CDFD11FC, C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\_mlir_libs\iree-compile.exe(0x00007FF7CDFD0000) + 0x11FC byte(s)
0x00007FFA77997614, C:\WINDOWS\System32\KERNEL32.DLL(0x00007FFA77980000) + 0x17614 byte(s), BaseThreadInitThunk() + 0x14 byte(s)
0x00007FFA790426A1, C:\WINDOWS\SYSTEM32\ntdll.dll(0x00007FFA78FF0000) + 0x526A1 byte(s), RtlUserThreadStart() + 0x21 byte(s)

Invoked with:
 iree-compile.exe C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=C:\Users\sk8er\AppData\Local\Temp\_MEI83882\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host --iree-vulkan-target-env=#vk.target_env<v1.3, r(120), [VK_KHR_16bit_storage, VK_KHR_8bit_storage, VK_KHR_shader_float16_int8, VK_KHR_spirv_1_4, VK_KHR_storage_buffer_storage_class, VK_KHR_variable_pointers, VK_EXT_subgroup_size_control, VK_NV_cooperative_matrix], AMD:DiscreteGPU, #vk.caps< maxComputeSharedMemorySize = 65536, maxComputeWorkGroupInvocations = 1024, maxComputeWorkGroupSize = dense<[1024, 1024, 1024]>: vector<3xi32>, subgroupSize = 64, subgroupFeatures = 255: i32, minSubgroupSize = 32, maxSubgroupSize = 64, shaderFloat16 = unit, shaderFloat64 = unit, shaderInt8 = unit, shaderInt16 = unit, shaderInt64 = unit, storageBuffer16BitAccess = unit, storagePushConstant16 = unit, uniformAndStorageBuffer16BitAccess = unit, storageBuffer8BitAccess = unit, storagePushConstant8 = unit, uniformAndStorageBuffer8BitAccess = unit, variablePointers = unit, variablePointersStorageBuffer = unit, cooperativeMatrixPropertiesNV = [#vk.coop_matrix_props<mSize = 16, nSize = 16, kSize = 16, aType = f16, bType = f16, cType = f16, resultType = f16, scope = #vk.scope<Subgroup>>] >> --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs -iree-vulkan-target-triple=rdna3-7900-windows

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.`

**Comment by powderluv** [comment]
Can you please make sure you don't have LLPC set to zero?

**Comment by powderluv** [comment]
Also can you please ensure you have enough system RAM and pagefile since it seems to be running out of memory during compile
