### ISSUE TITLE
Shark trying to open a random json and failing to render image

### ISSUE THREAD

**Issue by nivo92** [nod-ai/SHARK#1177]
For some reason the program is trying to open this medal-vulkan32.json file (medal.tv is a program to record gameplay etc) i disinstalled the program a long time ago, but i noticed that on the shark console this error about medal-vulka32.json and gog galaxy were showing, i decided to delete them from appdata to get rid of the errors, the galaxy error is not showing anymore but for some reason this medal-vulkan32.json is still saved in the loader (i'm new to this but i presume is some kind of list that tells the program to load the file), i uninstalled vulkan and reinstalled it, i tried to check the registry to see if something about medal was there, used a new version of shark, deleted everything about shark but the error is still there.

here the console paste:

shark_tank local cache is located at C:\Users\Nicola\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
vulkan devices are available.
cuda devices are not available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Found device AMD Radeon RX 6650 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
torch\jit\_check.py:172: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`.
  warnings.warn("The TorchScript type system doesn't support "
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\euler_scale_model_input_1_672_576fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\euler_scale_model_input_1_672_576fp16.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\euler_step_1_672_576fp16.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\euler_step_1_672_576fp16.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
Inferring base model configuration.
Downloading (…)ch_model.safetensors: 100%|████████████████████████████████████████| 3.46G/3.46G [07:23<00:00, 7.82MB/s]
huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Nicola\.cache\huggingface\diffusers. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
Downloading (…)ain/unet/config.json: 100%|█████████████████████████████████████████████| 911/911 [00:00<00:00, 902kB/s]
safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\unet1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\unet1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
Downloading (…)ch_model.safetensors: 100%|██████████████████████████████████████████| 335M/335M [00:44<00:00, 7.60MB/s]
Downloading (…)main/vae/config.json: 100%|█████████████████████████████████████████████| 553/553 [00:00<00:00, 364kB/s]
torch\fx\node.py:250: UserWarning: Trying to prepend a node to itself. This behavior has no effect on the graph.
  warnings.warn("Trying to prepend a node to itself. This behavior has no effect on the graph.")
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\vae1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\vae1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1032, in process_api
  File "gradio\blocks.py", line 858, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 448, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 122, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 356, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 553, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

Found device AMD Radeon RX 6650 XT. Using target triple rdna2-unknown-windows.
Tuned models are currently not supported for this setting.
loading existing vmfb from: C:\Users\Nicola\Desktop\new shark\euler_scale_model_input_1_672_576fp16.vmfb
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
loading existing vmfb from: C:\Users\Nicola\Desktop\new shark\euler_step_1_672_576fp16.vmfb
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
Deleted:  C:\Users\Nicola\Desktop\new shark\unet1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Deleted:  C:\Users\Nicola\Desktop\new shark\vae1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Inferring base model configuration.
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\unet1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\unet1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
No vmfb found. Compiling and saving to C:\Users\Nicola\Desktop\new shark\vae1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb
Using target triple -iree-vulkan-target-triple=rdna2-unknown-windows from command line args
Saved vmfb in C:\Users\Nicola\Desktop\new shark\vae1_64_672_576_fp16_stable-diffusion-2-1-base_vulkan.vmfb.
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan64.json
ERROR: [Loader Message] Code 0 : loader_get_json: Failed to open JSON file C:\Users\Nicola\AppData\Local\Medal\recorder-3.618.0\Host\medal-vulkan32.json
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Retrying with a different base model configuration
Traceback (most recent call last):
  File "gradio\routes.py", line 384, in run_predict
  File "gradio\blocks.py", line 1032, in process_api
  File "gradio\blocks.py", line 858, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 448, in async_iteration
  File "apps\stable_diffusion\scripts\txt2img.py", line 122, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 356, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 553, in __call__
SystemExit: Cannot compile the model. Please create an issue with the detailed log at https://github.com/nod-ai/SHARK/issues

**Comment by powderluv** [comment]
the medal-vulkan32.json error is because it left something in your registry. You will see that error everytime you run `vulkaninfo` even without SHARK. 

For the root cause of the crash can you confirm which build you are on ? Please don't use anything more than 592 since they are broken on RDNA2 (working on a fix.

**Comment by nivo92** [comment]
thanks for answering, i decided to switch to the stable version (i was on the latest and everything was working before deleting the medal file) and it seems to be working at the moment, the error is gone too for some reason. sorry for wasting your time and thanks for the program i hope it comes out well in the future
