### ISSUE TITLE
Use TEmpFileSaver API in IREE

### ISSUE THREAD

**Issue by powderluv** [nod-ai/SHARK#120]
Use TempFileSAver to save each PyTest output artifacts and recreate if the test fails. 

looks like you can also write your own TempFileSaver to do whatever you want (see the section just below that), like in this test: https://github.com/google/iree/blob/427a94a09be70631c5d9f89d12616bb7f1954257/compiler/src/iree/compiler/API/python/test/tools/compiler_core_test.py#L176-L199

https://discord.com/channels/689900678990135345/689900680009482386/985726147448950805

**Comment by monorimet** [comment]
#149 
Just need to get these tests refactored for importer/downloader

**Comment by monorimet** [comment]
Is this still necessary now that we have generate_sharktank? Perhaps we can add options to generate_sharktank to save the command line string for iree-compile if we want equivalent functionalities between what we have and what IREE TempFileSaver gives us.
