### ISSUE TITLE
Mark tests that require IMPORTER=1 tools

### ISSUE THREAD

**Issue by powderluv** [nod-ai/SHARK#123]
Importer tools other than torch-mlir tools need to be marked so pytests can run on venvs that dont have IMPORTER=1

**Comment by powderluv** [comment]
also add benchmarks and mark benchmarks

**Comment by monorimet** [comment]
Write results of frontend/python/c benchmarks on model tests to a .txt file located in the current working directory.

**Comment by powderluv** [comment]
.csv please

**Comment by monorimet** [comment]
Original issue solved in https://github.com/nod-ai/SHARK/pull/199

Filing separate issue for remaining work on benchmarks
