### ISSUE TITLE
shark euler vmfb doesn't have a device qualifier 

### ISSUE THREAD

**Issue by powderluv** [nod-ai/SHARK#1280]
So if you switched between a vulkan device and cuda device (on nvidia) we try to run the vulkan vmfb.

**Comment by monorimet** [comment]
Didn't see this until now. I have time to fix it today.

**Comment by monorimet** [comment]
Closing, as this is resolved by https://github.com/nod-ai/SHARK/commit/133c1bcaddfd9a507ce9dbe045294eb3751c9adc
