### ISSUE TITLE
Shark errors out v673- failed to legalize operation

### ISSUE THREAD

**Issue by dtroupe2** [nod-ai/SHARK#1299]
Verson 673
I get this error. <unknown>:0: error: failed to legalize operation 'gpu.subgroup_mma_store_matrix' that was explicitly marked illegal
<img width="1163" alt="Screenshot 2023-04-13 082502" src="https://user-images.githubusercontent.com/70831799/231772845-2a443c5e-acb2-4462-8f6d-3f6851c7a12a.png">

**Comment by yzhang93** [comment]
@dtroupe2 We are aware of the issue. We'll release 675 which has the fix later today.

**Comment by m68k-fr** [comment]
Any news ?
Running on an 6800XT (RDNA2) I'm still having this issue on 667 (iree 367)
