### ISSUE TITLE
vulkan devices are not available(7900xtx)

### ISSUE THREAD

**Issue by PennyFranklin** [nod-ai/SHARK#1305]
![屏幕截图 2023-04-16 201233](https://user-images.githubusercontent.com/104998459/232309407-741033a6-1458-498b-86a7-1937ce63b596.png)
only run with cpu,with the latest gpu driver

**Comment by Lumpsack** [comment]
I'm presuming you've tried the drop down list.
Not sure what to add other than its working for me - I've Windows 11, latest AMD adrenaline drivers for the 7900xtx and running shark_sd_20230410_670.exe

**Comment by PennyFranklin** [comment]
🤔that is wired

**Comment by GoZippy** [comment]
did you use the drop down to select the model and the correct device?

**Comment by PennyFranklin** [comment]
> did you use the drop down to select the model and the correct device?

i only can choose the CPU divide, the dashboard didn't give the 7900xtx vulkan choice

**Comment by GoZippy** [comment]
are you building your own or using the release? CLI? download latest release and try again...

**Comment by PennyFranklin** [comment]
still not working:( i've tried the latest release and use the --clear_all command
![屏幕截图 2023-04-24 125349](https://user-images.githubusercontent.com/104998459/233903699-6dab5e11-1944-40b1-a46d-0cdfe8f04a4b.png)

**Comment by powderluv** [comment]
Can you please check the version of AMD Adrenaline driver? Is it 23.5.x ? Also what is the output of vulkaninfo ?
