### ISSUE TITLE
Change tokenizer in opt_torch_test.py

### ISSUE THREAD

**Issue by giuliacassara** [nod-ai/SHARK#1455]
From 
`       tokenizer = GPT2Tokenizer.from_pretrained(model_name)
`
Change into :
`tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=False)`

The reason is explained [here](https://huggingface.co/docs/transformers/model_doc/opt)

**Comment by monorimet** [comment]
https://github.com/nod-ai/SHARK/commit/3cddd01b10ccab1c89ff7d70aa0223f2b247614e implements this change. Thanks!!
