### ISSUE TITLE
Add procedure to clear _MEI files in temp upon closing or add to --clear_all

### ISSUE THREAD

**Issue by dtroupe2** [nod-ai/SHARK#1480]
I've noticed as long as I have been using SHARK that it generates, but does not remove, a lot of _MEI folders in C:\Users\[USERNAME]\AppData\Local\Temp which can be quite sizable and use a lot of storage space over time.

I've been using a .bat file script I made to remove them (See below). Would it be possible to add a similar feature into the .exe for cleanup?

.bat script:

@echo off
setlocal

set "dir=C:\Users\dtrou\AppData\Local\Temp"
set "prefix=_MEI"

echo Deleting folders starting with %prefix% in %dir%...

REM Disable confirmation prompt before deleting folders
set "confirm_flag=/s /q"

for /f "delims=" %%f in ('dir /b /ad "%dir%\%prefix%*"') do (
    echo Deleted: "%dir%\%%f"
    rd %confirm_flag% "%dir%\%%f"
)

echo Deletion complete. This window will close in 3 seconds.
timeout /t 3 > nul

endlocal

Thanks Darrell (Ramz)

**Comment by KatarinaKubiniova** [comment]
Hello, i will look at this if you dont mind. How often should these files get deleted for example after each generation or program close?

**Comment by dtroupe2** [comment]
I think after program close should be sufficient. That is usually when I run my script.

**Comment by dtroupe2** [comment]
> I think after program close should be sufficient. That is usually when I run my script.
