### ISSUE TITLE
Releases 800 and below crash in amdvlk64.dll with AMD 23.7.1 driver.  804 crashes with error in the python.  

### ISSUE THREAD

**Issue by NeedsMoar** [nod-ai/SHARK#1636]
I'd really rather not have to revert to an older video driver (mainly since reboots take forever between BMC overhead and checking 512GB of ECC RDIMMs) but it looks like I'm stuck doing so for now...  AMD upped the Vulkan version to v1.3.250 and added some extensions...   

### 23.7.1 - July 6th, 2023

[AMD Software: Adrenalin Edition 23.7.1 Release Notes | AMD](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-7-1)

[VK_KHR_cooperative_matrix](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_cooperative_matrix.html) for Radeon™ RX 7000 series
[VK_KHR_ray_tracing_position_fetch](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_ray_tracing_position_fetch.html) for Radeon™ RX 6000 and newer series
[VK_KHR_video_decode_h264](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_video_decode_h264.html)
[VK_KHR_video_decode_h265](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_video_decode_h265.html)
[VK_KHR_video_decode_queue](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_video_decode_queue.html)
[VK_KHR_video_queue](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_video_queue.html)
[VK_EXT_device_address_binding_report](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_device_address_binding_report.html)
[VK_VALVE_mutable_descriptor_type](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_VALVE_mutable_descriptor_type.html)
[VK_EXT_mutable_descriptor_type](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_mutable_descriptor_type.html)
[VK_EXT_dynamic_rendering_unused_attachments](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_EXT_dynamic_rendering_unused_attachments.html)

<800:
```
Faulting application name: nodai_shark_sd_20230705_800.exe, version: 0.0.0.0, time stamp: 0x64a65959
Faulting module name: amdvlk64.dll, version: 31.0.21001.45002, time stamp: 0x64921e0d
Exception code: 0xc0000094
Fault offset: 0x0000000001bee06b
Faulting process id: 0x8c04
Faulting application start time: 0x01d9b1578b5a890c
Faulting application path: C:\Programs\Shark\nodai_shark_sd_20230705_800.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0393367.inf_amd64_6fba1387e8658583\B393268\amdvlk64.dll
Report Id: 8c21ff9e-3060-4ec6-8080-2d8da9084702
Faulting package full name: 
Faulting package-relative application ID: 
```

804:
```
Loading flatbuffer at C:\Programs\Shark\clip_1_64_512_512_fp16_tuned_stable-diffusion-2-1-base_vulkan.vmfb as a mmapped file
Traceback (most recent call last):
  File "gradio\routes.py", line 437, in run_predict
  File "gradio\blocks.py", line 1346, in process_api
  File "gradio\blocks.py", line 1090, in call_function
  File "gradio\utils.py", line 341, in async_iteration
  File "gradio\utils.py", line 334, in __anext__
  File "anyio\to_thread.py", line 33, in run_sync
  File "anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 807, in run
  File "gradio\utils.py", line 317, in run_sync_iterator_async
  File "ui\txt2img_ui.py", line 186, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_txt2img.py", line 123, in generate_images
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 450, in encode_prompts_weight
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 851, in get_weighted_text_embeddings
TypeError: 'NoneType' object cannot be interpreted as an integer
```

For reasons of sanity, I'm not using the advanced install and probably won't unless it becomes absolutely necessary for some reason.   I like that a wrapped executable is provided, it keeps everything contained... mostly.  I suspect it won't help, anyway, we just need a stable build linked against the new version of the vulkan DLL.  Unfortunately I can't find the old version anywhere on my system or I'd try dropping it in next to the shark executable.

**Comment by one-lithe-rune** [comment]
@NeedsMoar FWIW Advanced install doesn't like those drivers on rdna3 either.

**Comment by one-lithe-rune** [comment]
`--no-use_tuned` makes things work for me with the 23.7.1 drivers on rdna3 with the advanced install, although obviously it's slower. That's probably worth a try.

(suspect the error on 804 you're getting might a different thing though)

**Comment by powderluv** [comment]
I think a few issues were fixed over the weekend. There are two outstanding issues 23.7.1 is broken and we are following up with AMD on it (workaround is to use `--no-use_tuned`) and img2img is broken and we are following up with IREE team on it and will provide an update tomorrow.

**Comment by NeedsMoar** [comment]
Thanks.  I found the img2img being broken with no-use_tuned but hadn't posted it yet so glad it's not just me.  --no-use_tuned honestly isn't a heck of a lot slower on this driver version / shark version than tuned was on the previous for me (maybe 2.5it/s less on 512x768) so turning it on isn't as big a deal as I'd have thought.  I did still hit the NoneType on versions past 810 but haven't pulled anything newer yet so I'll check whatever the newest is out later.  I finally broke down and installed Python standalone to run ComfyUI and hopefully figure out how to get LoRAs training working on shark so I should just be able to do the advanced install and maybe try to fix things that break and provide better feedback.  :D

Off-topic but it'll be interesting to see how SDXL performs on Shark when it's supported.  I'm currently running it on ComfyUI via torch-directml which is very poorly supported on there (lots of broken schedulers and unsupported op errors that required digging into the source to find what I could actually use) and it's going at about 1.7it/s during the first model and 2.4it/s during the refiner but based on the speed of regular SD 1.4/2.1 based models it's probably 5x slower than shark to begin with.  I fear how gigantic the flatbuffers will be with that model though, the main checkpoints + subdirectories are 91GB for the base + refiner.

I'd love to see the ability to chain LoRAs that's available in Comfy ported over to shark somehow, although I don't know how it would work out since shark needs to compile the LoRAs on top of the base model and it would start eating up disk even faster with the chained combinations.

Thanks for looking into it and your work on this.  It's been getting incrementally faster by the release since I started messing with it a couple of months ago, building flatbuffers has really shot up in speed since then.

**Comment by NeedsMoar** [comment]
Everything works with 23.7.2 including img2img in the current release (819) so I'm closing this one;   newer versions either fail to compile models, have ~30-40% performance regressions, or freeze at the VAE loading phase but those things are all seemingly unrelated to this.
