### ISSUE TITLE
Add hyperlinks to README's Model list

### ISSUE THREAD

**Issue by raikonenfnu** [nod-ai/SHARK#172]
-Let's make it easier for users to browse and find models in SHARK, by putting up hyperlink in the text part of the model's name (i.e BERT, Albert, Alexnet, etc) which links to their respective tank model directory (e.g [bert link](https://github.com/nod-ai/SHARK/tree/main/tank/pytorch/bert-base-uncased), [albert link](https://github.com/nod-ai/SHARK/tree/main/tank/pytorch/albert-base-v2), [alexnet link](https://github.com/nod-ai/SHARK/tree/main/tank/pytorch/alexnet)).

**Comment by monorimet** [comment]
The tank directory has been refactored so all models are listed together -- they don't have their own directories or scripts.
Closing this issue -- feel free to open it if the ease of use still seems to be an issue @raikonenfnu
