### ISSUE TITLE
When --local_shark_tank is specified, --clear_all still only deletes the Users\Name\.local\shark_tank (default) directory

### ISSUE THREAD

**Issue by NeedsMoar** [nod-ai/SHARK#1751]
See title. I'm not sure of the importance of this since shark seems to pull the tuning files every time it uses them anyway but someone should look into this since it'll cause bad behavior if something that relies on actually being cleared is placed there in the future. 

Probably belongs with:
#1458 and #1729
since it relates to cleaning up the mess of code surrounding paths.

**Comment by dan-garvey** [comment]
Fixed in #1833

**Comment by dan-garvey** [comment]
(@NeedsMoar thanks for taking the time to file)
