### ISSUE TITLE
Shark 909 broken

### ISSUE THREAD

**Issue by Arcadia245** [nod-ai/SHARK#1794]
Sorry I can't copy and paste the error code, but I did screenshot it: 

https://cdn.discordapp.com/attachments/973663920290164818/1144395627241947197/image.png

**Comment by FaterSteve** [comment]
The latest version that worked for me was 907.

**Comment by Arcadia245** [comment]
Closing, fixed with 916.

**Comment by Arcadia245** [comment]
Closing, fixed with 916.
