### ISSUE TITLE
Unprecendented VAE Load Times

### ISSUE THREAD

**Issue by njsharpe** [nod-ai/SHARK#1816]
20230904.931 resolves #1813 but causes another issue where the VAE load time after compile is _much_ longer than it has been in the past. I believe this was resolved once before, but it seems the issue has returned. Previously, I had seen times of typically less than 400s for a full compile & load, but now current generation for a new combination can take upwards of 1500s, where VAE load alone takes roughly 1300s.

**Comment by powderluv** [comment]
This is still a Vulkan Driver bug and is being actively worked on. The next driver release could speed it up a bit but don't know when the full fix would be available. The VAE compile should take about 17s currently.  

While we wait for the vulkan driver fix we likely will have ROCM path fully enabled (with wmma).

**Comment by njsharpe** [comment]
> The VAE compile should take about 17s currently.

To clarify, the compile is fast as you claim. The load after the compile is the bottleneck. I'll keep this open for a bit as changes continue to roll in for ROCm.

**Comment by powderluv** [comment]
actually there is another compiler that gets invoked when loading the vmfb. This is the LLPC Spir-v to ISA compiler.

**Comment by njsharpe** [comment]
Resolved Adrenaline 23.9.3 from what I can see. Have get to hit these 2000s+ times on first generation.
