### ISSUE TITLE
Input image masks on Image2Image does not seem to do anything

### ISSUE THREAD

**Issue by DiffusionAllusion** [nod-ai/SHARK#2038]
I get the exact same results when using the draw mask on image-to-image. Is this a bug, or is it not supported? And if it's not supported, maybe the draw feature should be disabled for these?

I hope it is supposed to work, because it would be really nice to be able to ignore some areas from img2img, since some models don't support inpainting.

**Comment by monorimet** [comment]
we can't just get inpainting for free, unfortunately. It will be less confusing after we overhaul the SD UI.
