### ISSUE TITLE
After compiling Vulkan shaders, multiple errors ensue

### ISSUE THREAD

**Issue by 4141429** [nod-ai/SHARK#2085]
After running SHARK on a fresh install, selecting stabilityai/stable-diffusion-2-1-base, generating the default prompt, and compiling Vulkan shaders i receive this error:

[a.txt](https://github.com/nod-ai/SHARK/files/14151814/a.txt)
(logs from cmd prompt)

**Comment by f1am3d** [comment]
seems like the project is abandoned, since no response from the team for last several months

**Comment by 4141429** [comment]
yeah, just had to run the stable version
