### ISSUE TITLE
GPT-2 torch to tosa

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK#338]
The python script to run:

[gpt2tosa.py](https://gist.github.com/AmosLewis/9b929414d5677afda3528122f92bbc73)

**Comment by AmosLewis** [comment]
This linalg patch can test tosa with tinny change [https://github.com/nod-ai/SHARK/pull/341](https://github.com/nod-ai/SHARK/pull/341). But now get the bug 

```
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.constant.int'
note: see current operation: %0 = "torch.constant.int"() {value = 5 : i64} : () -> !torch.int


Error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torch-backend-to-tosa-backend-pipeline' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
```

**Comment by nithinsubbiah** [comment]
This error is probably due to a missing op or unhandled variables in an op. Check all the ops where `%0` is used to triage the error further

**Comment by AmosLewis** [comment]
Byte bug patch https://github.com/llvm/torch-mlir/pull/1384 and View Bug Patch https://github.com/llvm/torch-mlir/pull/1384 , after apply this two patch , we got broadcast_to bug.

```
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/SHARK/tank/gpt2_torch/gpt2.py", line 89, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 262, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
error: failed to legalize operation 'torch.aten.broadcast_to' that was explicitly marked illegal
note: see current operation: %469 = "torch.aten.broadcast_to"(%467, %468) : (!torch.vtensor<[],i1>, !torch.list<int>) -> !torch.vtensor<[1,1,5,5],i1>


Error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='torch-backend-to-tosa-backend-pipeline' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by vivekkhandelwal1** [comment]
> Byte bug patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) and View Bug Patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) , after apply this two patch , we got broadcast_to bug.

Actually, bert to tosa is also failing on this op. I think due to some upstream changes this is happening. I would try to support more cases for this ops lowering.

**Comment by vivekkhandelwal1** [comment]
> Byte bug patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) and View Bug Patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) , after apply this two patch , we got broadcast_to bug.
> 
> ```
> Traceback (most recent call last):
>   File "/home/chi/src/ubuntu20/shark/SHARK/tank/gpt2_torch/gpt2.py", line 89, in <module>
>     module = torch_mlir.compile(
>   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 262, in compile
>     run_pipeline_with_repro_report(
>   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
>     raise TorchMlirCompilerError(trimmed_message) from None
> torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
> error: failed to legalize operation 'torch.aten.broadcast_to' that was explicitly marked illegal
> note: see current operation: %469 = "torch.aten.broadcast_to"(%467, %468) : (!torch.vtensor<[],i1>, !torch.list<int>) -> !torch.vtensor<[1,1,5,5],i1>
> 
> 
> Error can be reproduced with:
> $ torch-mlir-opt -pass-pipeline='torch-backend-to-tosa-backend-pipeline' /tmp/_lambda.mlir
> Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
> ```

This error is fixed with the following patch: https://github.com/llvm/torch-mlir/pull/1429. But there are many other ops whose TorchToTosa lowering needs to be added, like: 
```
torch.aten.arange.start_step, torch.prim.NumToTensor.Scalar, torch.aten.to.dtype, torch.valsem.aten.copy, torch.aten.where.self
```

**Comment by AmosLewis** [comment]
> > Byte bug patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) and View Bug Patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) , after apply this two patch , we got broadcast_to bug.
> > ```
> > Traceback (most recent call last):
> >   File "/home/chi/src/ubuntu20/shark/SHARK/tank/gpt2_torch/gpt2.py", line 89, in <module>
> >     module = torch_mlir.compile(
> >   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 262, in compile
> >     run_pipeline_with_repro_report(
> >   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
> >     raise TorchMlirCompilerError(trimmed_message) from None
> > torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
> > error: failed to legalize operation 'torch.aten.broadcast_to' that was explicitly marked illegal
> > note: see current operation: %469 = "torch.aten.broadcast_to"(%467, %468) : (!torch.vtensor<[],i1>, !torch.list<int>) -> !torch.vtensor<[1,1,5,5],i1>
> > 
> > 
> > Error can be reproduced with:
> > $ torch-mlir-opt -pass-pipeline='torch-backend-to-tosa-backend-pipeline' /tmp/_lambda.mlir
> > Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
> > ```
> 
> This error is fixed with the following patch: [llvm/torch-mlir#1429](https://github.com/llvm/torch-mlir/pull/1429). But there are many other ops whose TorchToTosa lowering needs to be added, like:
> 
> ```
> torch.aten.arange.start_step, torch.prim.NumToTensor.Scalar, torch.aten.to.dtype, torch.valsem.aten.copy, torch.aten.where.self
> ```

https://github.com/AmosLewis/torch-mlir/tree/gpt-tosa. I tried to repeat the error with upstream/main + 1429 + 1384. But I got the old 'torch.constant.int' issue. Are you 5 ops got from this issue?

**Comment by AmosLewis** [comment]
Some usefully tosa support link https://discourse.llvm.org/t/basic-tosa-support/4432/7

**Comment by AmosLewis** [comment]
> > Byte bug patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) and View Bug Patch [llvm/torch-mlir#1384](https://github.com/llvm/torch-mlir/pull/1384) , after apply this two patch , we got broadcast_to bug.
> > ```
> > Traceback (most recent call last):
> >   File "/home/chi/src/ubuntu20/shark/SHARK/tank/gpt2_torch/gpt2.py", line 89, in <module>
> >     module = torch_mlir.compile(
> >   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 262, in compile
> >     run_pipeline_with_repro_report(
> >   File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
> >     raise TorchMlirCompilerError(trimmed_message) from None
> > torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering Torch Backend IR -> TOSA Backend IR failed with the following diagnostics:
> > error: failed to legalize operation 'torch.aten.broadcast_to' that was explicitly marked illegal
> > note: see current operation: %469 = "torch.aten.broadcast_to"(%467, %468) : (!torch.vtensor<[],i1>, !torch.list<int>) -> !torch.vtensor<[1,1,5,5],i1>
> > 
> > 
> > Error can be reproduced with:
> > $ torch-mlir-opt -pass-pipeline='torch-backend-to-tosa-backend-pipeline' /tmp/_lambda.mlir
> > Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.
> > ```
> 
> This error is fixed with the following patch: [llvm/torch-mlir#1429](https://github.com/llvm/torch-mlir/pull/1429). But there are many other ops whose TorchToTosa lowering needs to be added, like:
> 
> ```
> torch.aten.arange.start_step, torch.prim.NumToTensor.Scalar, torch.aten.to.dtype, torch.valsem.aten.copy, torch.aten.where.self
> ```
[torch.aten.arange.start_step](https://github.com/llvm/torch-mlir/pull/1442) MERGED
[torch.prim.NumToTensor.Scalar + torch.aten.to.dtype + torch.valsem.aten.copy](https://github.com/vivekkhandelwal1/torch-mlir/tree/tosa-valsem-copy-op) WIP
 [torch.aten.where.self](https://github.com/llvm/torch-mlir/pull/1454) READY FOR REVIEW

**Comment by AmosLewis** [comment]
General update conclusion for right now.

[aten.view](https://github.com/llvm/torch-mlir/pull/1353) MERGED
[aten.sum.dim_IntList](https://github.com/llvm/torch-mlir/pull/1387) test MERGED
[aten.broadcast_to](https://github.com/llvm/torch-mlir/pull/1429) MERGED
[aten.clone](https://github.com/llvm/torch-mlir/pull/1388) MERGED
[torch.uint8 type support](https://github.com/llvm/torch-mlir/pull/1384) MERGED

[torch.aten.arange.start_step](https://github.com/llvm/torch-mlir/pull/1442) MERGED
[torch.aten.where.self](https://github.com/llvm/torch-mlir/pull/1454) READY FOR REVIEW
[torch.prim.NumToTensor.Scalar + torch.valsem.aten.copy + torch.aten.to.dtype](https://github.com/vivekkhandelwal1/torch-mlir/tree/tosa-valsem-copy-op)  3 op in one patch, first 2 ready, last one WIP

**Comment by AmosLewis** [comment]
```
Traceback (most recent call last):
  File "/home/chi/src/ubuntu20/shark/SHARK/tank/pytorch/gpt2/gpt2tosa.py", line 91, in <module>
    module = torch_mlir.compile(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/__init__.py", line 371, in compile
    run_pipeline_with_repro_report(
  File "/home/chi/src/ubuntu20/shark/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir/torch_mlir/compiler_utils.py", line 73, in run_pipeline_with_repro_report
    raise TorchMlirCompilerError(trimmed_message) from None
torch_mlir.compiler_utils.TorchMlirCompilerError: Lowering TorchScript IR -> Torch Backend IR failed with the following diagnostics:
error: unsupported by backend contract: tensor with unknown dtype
note: see current operation: %923 = "torch.aten.tanh"(%922) : (!torch.vtensor<[1,5,3072],f32>) -> !torch.vtensor<[1,5,3072],unk>
note: this is likely due to a missing case in RefineTypes


For Torch-MLIR developers, the error can be reproduced with:
$ torch-mlir-opt -pass-pipeline='builtin.module(torchscript-module-to-torch-backend-pipeline{backend-legal-ops=torch.aten.flatten.using_ints,torch.aten.native_layer_norm,torch.aten.linear})' /tmp/_lambda.mlir
Add '-mlir-print-ir-after-all -mlir-disable-threading' to get the IR dump for debugging purpose.

```

**Comment by AmosLewis** [comment]
```
Legalizing operation : 'torch.aten.view'(0x845add0) {
  %216 = "torch.aten.view"(%arg1, %215) : (!torch.tensor, !torch.list<int>) -> !torch.tensor

  * Fold {
  } -> FAILURE : unable to fold

  * Pattern : 'torch.aten.view -> ()' {
Trying to match "(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>"
    ** Failure : Only tensor types are currently supported
"(anonymous namespace)::ConvertAtenOp<mlir::torch::Torch::AtenViewOp>" result 0
  } -> FAILURE : pattern failed to match
} -> FAILURE : no matched legalization pattern
//===-------------------------------------------===//
<eval_with_key>.2:5:11: error: failed to legalize operation 'torch.aten.view' that was explicitly marked illegal
<eval_with_key>.2:5:11: note: see current operation: %27 = "torch.aten.view"(%arg1, %26) : (!torch.tensor, !torch.list<int>) -> !torch.tensor



%arg1: !torch.tensor {torch.type_bound = !torch.vtensor<[1,5],si64>}
%int-1 = torch.constant.int -1
%int5 = torch.constant.int 5
%0 = torch.prim.ListConstruct %int-1, %int5 : (!torch.int, !torch.int) -> !torch.list<int>
%1 = torch.aten.view %arg1, %0 : !torch.tensor, !torch.list<int> -> !torch.tensor
```

**Comment by AmosLewis** [comment]
The new tosa file with refine types bug fix: https://gist.github.com/AmosLewis/fd8b242db2b5f328fa56e9afa270cbd6
