### ISSUE TITLE
BERT torch to tosa

### ISSUE THREAD

**Issue by AmosLewis** [nod-ai/SHARK#339]

**Comment by vivekkhandelwal1** [comment]
As of now, there are two issues:
1.) With the folding of slice op. Particularly for this case:
```
//===-------------------------------------------===//
Processing operation : 'tosa.slice'(0x7a018b0) {
  %61 = "tosa.slice"(%39) {size = [1, 7], start = [0, 0]} : (tensor<1x512xi64>) -> tensor<1x7xi64>
```
It crashes at: https://github.com/llvm/llvm-project/blob/4d4ca6c9d036a06bf0723786112dd17e491b2f53/mlir/lib/Dialect/Tosa/IR/TosaCanonicalizations.cpp#L864, due to this assertion: https://github.com/llvm/llvm-project/blob/4d4ca6c9d036a06bf0723786112dd17e491b2f53/mlir/lib/IR/BuiltinAttributes.cpp#L1030-L1031. The reason is that the input element type from torch tensor is si64 while the assertion compares that with i64, hence it crashes. If you disable this assertion, then it folds the slice op.
2.) The lowering for two ops are missing namely: torch.aten.broadcast_to, torch.aten.clone

**Comment by vivekkhandelwal1** [comment]
Script to run: https://gist.github.com/pashu123/2c1495c5d99c06b755c07799cfd38f5d

Here's the torch-IR: https://gist.github.com/be17403f3a6b271cbb7ac16f935d8eaa

**Comment by vivekkhandelwal1** [comment]
Hi, the recent update is that the model now lowers from Torch to Tosa, but is giving a runtime error, while running it via shark:
```
Traceback (most recent call last):
  File "hf_minilm.py", line 99, in <module>
    shark_module.compile()
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/shark_inference.py", line 87, in compile
    self.shark_runner = SharkRunner(
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/shark_runner.py", line 81, in __init__
    ) = get_iree_compiled_module(
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/iree_utils/compile_utils.py", line 125, in get_iree_compiled_module
    flatbuffer_blob = compile_module_to_flatbuffer(
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/iree_utils/compile_utils.py", line 88, in compile_module_to_flatbuffer
    flatbuffer_blob = ireec.compile_str(
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark.venv/lib/python3.8/site-packages/iree/compiler/tools/core.py", line 277, in compile_str
    result = invoke_immediate(cl, immediate_input=input_bytes)
  File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark.venv/lib/python3.8/site-packages/iree/compiler/tools/binaries.py", line 194, in invoke_immediate
    process = subprocess.run(command_line, capture_output=True, **run_args)
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1848, in _communicate
    input_view = memoryview(self._input)
TypeError: memoryview: a bytes-like object is required, not 'torch_mlir._mlir_libs._mlir.ir.Module'
```
I'm using the following script to run this: https://gist.github.com/bb75a50ec40f07a3336685a05c5cc22a

Good news is that model is now lowerable from Torch to Tosa. I have added two patches in Torch-MLIR for the op lowerings that were missing: https://github.com/llvm/torch-mlir/pull/1386, https://github.com/llvm/torch-mlir/pull/1388. For the issue with the assertion in llvm, as of now I'm just disabling this assertion (https://github.com/llvm/llvm-project/blob/4d4ca6c9d036a06bf0723786112dd17e491b2f53/mlir/lib/IR/BuiltinAttributes.cpp#L1030-L1031) to get the model compiled. I have created an issue for this in the llvm-project, here: https://github.com/llvm/llvm-project/issues/57846. 

The bert tosa IR is available at: https://storage.googleapis.com/shark_tank/latest/bert-base-uncased_tosa/hf_minilm_ir.mlir

**Comment by vivekkhandelwal1** [comment]
The issue can be reproduced by using the following torch-mlir branch: https://github.com/vivekkhandelwal1/torch-mlir/tree/bert-tosa-model, and the following script: https://gist.github.com/bb75a50ec40f07a3336685a05c5cc22a

**Comment by vivekkhandelwal1** [comment]
The bert torch to tosa can be run using this script in the SHARK: https://github.com/nod-ai/SHARK/blob/main/tank/bert-base-uncased_tosa_torch/bert_base_uncased_tosa.py

**Comment by vivekkhandelwal1** [comment]
This patch adds the required support for broadcast: https://github.com/llvm/torch-mlir/pull/1429

**Comment by vivekkhandelwal1** [comment]
The fix for `si64` -> `i64` conversion is here: https://github.com/llvm/torch-mlir/pull/1436

**Comment by powderluv** [comment]
Nicely done

**Comment by ehuaa** [comment]
> Hi, the recent update is that the model now lowers from Torch to Tosa, but is giving a runtime error, while running it via shark:
> 
> ```
> Traceback (most recent call last):
>   File "hf_minilm.py", line 99, in <module>
>     shark_module.compile()
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/shark_inference.py", line 87, in compile
>     self.shark_runner = SharkRunner(
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/shark_runner.py", line 81, in __init__
>     ) = get_iree_compiled_module(
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/iree_utils/compile_utils.py", line 125, in get_iree_compiled_module
>     flatbuffer_blob = compile_module_to_flatbuffer(
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark/iree_utils/compile_utils.py", line 88, in compile_module_to_flatbuffer
>     flatbuffer_blob = ireec.compile_str(
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark.venv/lib/python3.8/site-packages/iree/compiler/tools/core.py", line 277, in compile_str
>     result = invoke_immediate(cl, immediate_input=input_bytes)
>   File "/home/vivek/work/02_07/vivekkhandelwal1-SHARK/shark.venv/lib/python3.8/site-packages/iree/compiler/tools/binaries.py", line 194, in invoke_immediate
>     process = subprocess.run(command_line, capture_output=True, **run_args)
>   File "/usr/lib/python3.8/subprocess.py", line 495, in run
>     stdout, stderr = process.communicate(input, timeout=timeout)
>   File "/usr/lib/python3.8/subprocess.py", line 1028, in communicate
>     stdout, stderr = self._communicate(input, endtime, timeout)
>   File "/usr/lib/python3.8/subprocess.py", line 1848, in _communicate
>     input_view = memoryview(self._input)
> TypeError: memoryview: a bytes-like object is required, not 'torch_mlir._mlir_libs._mlir.ir.Module'
> ```
> 
> I'm using the following script to run this: https://gist.github.com/bb75a50ec40f07a3336685a05c5cc22a
> 
> Good news is that model is now lowerable from Torch to Tosa. I have added two patches in Torch-MLIR for the op lowerings that were missing: [llvm/torch-mlir#1386](https://github.com/llvm/torch-mlir/pull/1386), [llvm/torch-mlir#1388](https://github.com/llvm/torch-mlir/pull/1388). For the issue with the assertion in llvm, as of now I'm just disabling this assertion (https://github.com/llvm/llvm-project/blob/4d4ca6c9d036a06bf0723786112dd17e491b2f53/mlir/lib/IR/BuiltinAttributes.cpp#L1030-L1031) to get the model compiled. I have created an issue for this in the llvm-project, here: [llvm/llvm-project#57846](https://github.com/llvm/llvm-project/issues/57846).
> 
> The bert tosa IR is available at: https://storage.googleapis.com/shark_tank/latest/bert-base-uncased_tosa/hf_minilm_ir.mlir

@vivekkhandelwal1 i ran into this runtime error again, can you tell me how you fix it? thanks
