### ISSUE TITLE
Add TorchInductor as a baseline of comparison

### ISSUE THREAD

**Issue by mariecwhite** [nod-ai/SHARK#364]
TorchInductor is outperforming other PyTorch compilers so it would be great if we can use this as a baseline. Reference: https://dev-discuss.pytorch.org/t/torchinductor-a-pytorch-native-compiler-with-define-by-run-ir-and-symbolic-shapes/747

**Comment by monorimet** [comment]
https://github.com/nod-ai/SHARK/pull/793
https://github.com/nod-ai/SHARK/pull/784
Thanks for this, Marie!
