### ISSUE TITLE
"Could not install torch-mlir" error on regular CI runs

### ISSUE THREAD

**Issue by ScottTodd** [nod-ai/SHARK#373]
The [`test_shark_model_suite` job on IREE's CI](https://github.com/iree-org/iree/blob/cb78faea7cdb392e2641967343b42455415a2c1a/.github/workflows/ci.yml#L452-L508) is failing, sample: https://github.com/iree-org/iree/actions/runs/3144865881/jobs/5111621410

https://github.com/iree-org/iree/commits/main
![image](https://user-images.githubusercontent.com/4010439/192841618-b16d935c-3e53-4d5f-90f8-be2294fe98b3.png)

Error logs include
```
ERROR: Could not find a version that satisfies the requirement torch-mlir (from versions: none)
ERROR: No matching distribution found for torch-mlir
Could not install torch-mlir
```

I suspect that https://github.com/nod-ai/SHARK/blob/9035a2eed3bee1e8afc5afb82690f5dcceadd775/setup_venv.sh#L74-L79 should be updated following https://github.com/llvm/torch-mlir/commit/1dfe5efe9ee8f58deabf9382b58894a00b2d440c /  https://github.com/llvm/torch-mlir/commit/8d3ca887df5ac5126fa3fc2ec3546c6322a4d066

**Comment by GMNGeoffrey** [comment]
This looks like https://github.com/iree-org/iree/issues/10479 and https://github.com/llvm/torch-mlir/issues/1374. It also suggests that we're grabbing the latest version of things dynamically from the network instead of using a pinned version (ideally already installed in a docker container). This way of doing is likely going to cause version skew issues.

**Comment by GMNGeoffrey** [comment]
I think disabling pending a fix makes sense. It's not giving us any coverage as is. But please also merge this change :-) I'd just put a "false" in the if condition here so we preserve the configuration

**Comment by GMNGeoffrey** [comment]
@mariecwhite FYI

**Comment by mariecwhite** [comment]
Thanks for handling this. @dan-garvey @monorimet

**Comment by ScottTodd** [comment]
Was this fixed by https://github.com/nod-ai/SHARK/pull/374? Want to try re-enabling the tests in IREE?

**Comment by mariecwhite** [comment]
PR to re-enable: https://github.com/iree-org/iree/pull/10587
