### ISSUE TITLE
MLIR/IREE driver on 5700XT has corrupted image using fp16

### ISSUE THREAD

**Issue by jdluzen** [nod-ai/SHARK#547]
I am currently on Windows11 with a 5700XT using the MLIR/IREE driver.
There appears to be image corruption using `fp16`, `fp32` works fine but is ~5.5x slower.
The cache directory `C:\Users\<username>\AppData\Local\AMD\VkCache\` was cleared after driver installs.
The .vmfbs were deleted (moved) for a regeneration, and the md5s were the same.

**Comment by qedawkins** [comment]
Looks like the cause was a recent change to use the FP16 version of CLIP whereas before we were always using FP32. #548 is a temporary fix while the correctness issue with CLIP FP16 are solved.

**Comment by jdluzen** [comment]
Thanks, I can also confirm that it works.

**Comment by qedawkins** [comment]
great, closing this then.
