### ISSUE TITLE
Vega 10 (Vega 56/64) Support

### ISSUE THREAD

**Issue by Vilberg** [nod-ai/SHARK#550]
As suggested filing a bug report with my vulkaninfo and vram size.

Following error when running with an AMD Vega GPU.
VRAM: 8GB HBM2

_Optimized kernel for your target device is not added yet.
            Contact SHARK Admin on discord[https://discord.com/invite/RUqY2h2s9u]
            or pull up an issue.
Target : deviceName        = Radeon RX Vega_

**Vulkan info output:**
[vulkan_info_vega10.txt](https://github.com/nod-ai/SHARK/files/10148727/vulkan_info_vega10.txt)

**Comment by PhaneeshB** [comment]
Hi @Vilberg you try this with the latest changes.
It should be able to choose target-triple as `rdna2-unknown-<OS>`
