### ISSUE TITLE
startup fails on Win11

### ISSUE THREAD

**Issue by devakm** [nod-ai/SHARK#587]
I installed the adrenaline driver, cleared the vkcache, and ran shark_sd.exe. I get this fatal exception:

xyz.str:731:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
xyz.str:22:3: note: called from
xyz.str:731:12: error: failed to serialize executables
xyz.str:22:3: note: called from
xyz.str:22:3: error: 'spirv.Bitcast' op mismatch in result type bitwidth 128 and operand type bitwidth 64
xyz.str:22:3: note: called from
xyz.str:745:12: error: failed to run translation of source executable to target executable for backend #hal.executable.target<"vulkan", "vulkan-spirv-fb", {spirv.target_env = #spirv.target_env<#spirv.vce<v1.3, [Shader, GroupNonUniform], [SPV_KHR_storage_buffer_storage_class, SPV_KHR_variable_pointers]>, api=Vulkan, #spirv.resource_limits<max_compute_workgroup_size = [128, 128, 64], subgroup_size = 64, cooperative_matrix_properties_nv = []>>}>
xyz.str:22:3: note: called from
xyz.str:745:12: error: failed to serialize executables
xyz.str:22:3: note: called from

Invoked with:
 iree-compile.exe C:\Users\aubre\AppData\Local\Temp\_MEI200562\iree\compiler\tools\..\_mlir_libs\iree-compile.exe - --iree-input-type=none --iree-vm-bytecode-module-output-format=flatbuffer-binary --iree-hal-target-backends=vulkan --iree-llvm-embedded-linker-path=C:\Users\aubre\AppData\Local\Temp\_MEI200562\iree\compiler\tools\..\_mlir_libs\iree-lld.exe --mlir-print-debuginfo --mlir-print-op-on-diagnostic=false --iree-llvm-target-cpu-features=host --iree-stream-resource-index-bits=64 --iree-vm-target-index-bits=64 --iree-util-zero-fill-elided-attrs --iree-flow-enable-conv-nchw-to-nhwc-transform --iree-flow-enable-padding-linalg-ops --iree-flow-linalg-ops-padding-size=32

Need more information? Set IREE_SAVE_TEMPS=/some/dir in your environment to save all artifacts and reproducers.

[9564] Failed to execute script 'index' due to unhandled exception!

**Comment by powderluv** [comment]
This usually happens with an unsupported card. Can you please attach your vulkaninfo and card name / vram etc?

**Comment by devakm** [comment]
RX480, 8Gb, see attached
[vulkaninfo.txt](https://github.com/nod-ai/SHARK/files/10183606/vulkaninfo.txt)

**Comment by devakm** [comment]
I am able to run SD using onnx without any issues, but it does not have a supported GUI that I can find.

**Comment by KaseyTheJackal** [comment]
Radeon RX 6700S, Windows 11, I can duplicate this

[vulkaninfo.txt](https://github.com/nod-ai/SHARK/files/10200261/vulkaninfo.txt)

**Comment by powderluv** [comment]
Please delete your shark tank in ~/.local/shark_tank. The formats changed a bit

**Comment by osefcorp** [comment]
> Please delete your shark tank in ~/.local/shark_tank. The formats changed a bit

it works!
