### ISSUE TITLE
Check CUDA version and enable the corresponding flag in IREE cuda 

### ISSUE THREAD

**Issue by powderluv** [nod-ai/SHARK#59]
`--iree-cuda-llvm-target-arch=sm_80` should be set with something like:

https://gist.githubusercontent.com/f0k/63a664160d016a491b2cbea15913d549/raw/7f3ada81a4807771f2e5fcfc20a4e60da8aced4f/cuda_check.py

**Comment by monorimet** [comment]
PR #66 should resolve this issue.
