### ISSUE TITLE
Option to autosave & embed info into image

### ISSUE THREAD

**Issue by xzuyn** [nod-ai/SHARK#650]
Currently you need to manually save them, it'd be nice to be able to have a toggle to auto save them with maybe part of the prompt in the file name (and if the file exists add a random number to the end so it doesn't get overwritten), and embed the info into the image.

**Comment by PhaneeshB** [comment]
Hi @xzuyn 
[This PR](https://github.com/nod-ai/SHARK/pull/790) addresses the issue of the image being overwritten and along with it gives a json file with the params used to generate the image
Give it a shot and let us know

**Comment by xzuyn** [comment]
Commit 3b2bbb7 seems to work well outputting my images and saving the settings i used, although the jpeg quality is quite low. I submitted a pull request to increase the quality. #801

**Comment by PhaneeshB** [comment]
#790 and #794 address this issue
