### ISSUE TITLE
auto output multiple images, and custom models

### ISSUE THREAD

**Issue by al3k87** [nod-ai/SHARK#712]
I want to be able to set a output dir, and den hit like a multi render with adjustable iterations, so I can just leave it for a few hours and a get a folder with for example 1000 images with the same prompt but different seed for each iteration,I made this for mye onnx build python script, but I wanna use this cause its insanely fast now! my previous iteration time was 22sec with 50 inference steps.
NICE WORK!

Also it would be cool to add .ckpt trained models of own images exported from google colab.

**Comment by al3k87** [comment]
now its 3.39 sec to generate image on my 7900 XT! this is a game breaker!

**Comment by paranoiks** [comment]
What versions of Adrenaline do you have installed?

**Comment by PhaneeshB** [comment]
Hi @al3k87 PR #812 adds the functionality to run SD with same prompt for random seeds
give it a shot and let us know it works for you 

Support for adding custom models is underway! 
feel free to reopen this issue incase the multi-run functionality doesn't work for you
closing this issue. Thanks
