### ISSUE TITLE
VK_ERROR_OUT_OF_DEVICE_MEMORY generating in Web UI, on Windows, Radeon VII 16GB

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#719]
Getting the attached errors starting a generation in the web ui, on a clean clone with head at  136021424c3223f10b5ad2fb12f23aa46e32a0fd

Card is AMD Radeon VII 16GB, Window 10, have nuked ~\.local\shark-tank etc. 

Have an older clone, with my futzing about on a branch off of the 20221215.386 tag at 6508e3fcc9c1f0c35cc56cc60207e8c36eb41a58, with it's own --local-shark-tank set and previously generated .vmfb's, which is still working.

[nod-ai-shark-web-VK_OUT_OF_DEVICE_MEMORY.log](https://github.com/nod-ai/SHARK/files/10297558/nod-ai-shark-web-VK_OUT_OF_DEVICE_MEMORY.log)

**Comment by Muramas** [comment]
406 downwards work but any of the new ones give this error for me.

**Comment by powderluv** [comment]
Please try 411

**Comment by Muramas** [comment]
Tried 412 and that works but it takes much longer to start up than previous version. That being said, having the ability to swap between models is awesome.

**Comment by one-lithe-rune** [comment]
Running on tag 411 checked out worked for me just now. 

However tag 411 looks to be against the same commit as I was running against in the original report. 

.\setup.venv.ps1 pulled in the iree-compiler and iree-runtime from today's SHARK Runtime candidate-20221226.255, so a change there at some point was probably what fixed it. 

Which particular runtime version had the fix I couldn't tell you, as .\setup.venv always seems to pull in the latest at the time you run it, rather than whichever was the latest at the tag. 

I admit don't know much about Python, so I was wasn't expecting this behavior coming from Ruby and JavaScript where there would be a Gemfile.lock and a yarn.lock. I'm guessing Python may not have an equivalent? Or possibly I'm doing something wrong?

I'm not currently running the .exe versions. So it's solved here unless you need more info from me.

**Comment by powderluv** [comment]
closing this as fixed.
