### ISSUE TITLE
Can the Shark_tank cache files be in the local directory?

### ISSUE THREAD

**Issue by Muramas** [nod-ai/SHARK#738]
I see that over 27GB of shark's cache files are going into my user directory which is on a different drive that I use for windows and is filling up the drive.

It would be nice to put the cached version on the same drive / location or be asked where to put it.

I can see this being a big issue for non-technical users who have no good way of finding these files and are having similar issues

**Comment by PhaneeshB** [comment]
Hi @Muramas 
you can use the `--local_tank_cache=<path>` flag to store the cached files in the appropriate location.

Do try this an update if that is not working for you.
Thanks

**Comment by Muramas** [comment]
Was able to check it out and it worked. It might be good to add this to the main page information.
Thanks,

**Comment by AbhiSharma1210** [comment]
Where to set this flag?
