### ISSUE TITLE
Can't we use regular AMD Radeon Software to generate images?

### ISSUE THREAD

**Issue by excelsior091224** [nod-ai/SHARK#767]
I used this software after installing AMD Software: Adrenalin Edition 22.11.1 for MLIR/IREE Driver according to the guide below and successfully generated images.
https://github.com/nod-ai/SHARK/blob/main/shark/examples/shark_inference/stable_diffusion/stable_diffusion_amd.md
However, the installation of the MLIR/IREE Driver caused the mouse pointer to shift position.
(The guide says "if you use a larger-than-default mouse pointer", but this problem occurs even though the mouse pointer on my PC is size 1 from the start, and changing the size does not solve the problem.)
This is interfering with my work on my PC, so I have reverted to the normal version of AMD Radeon Software (22.11.2 Recommended (WHQL)).
However, when I did so, this software now produces only black images.
If the special driver causes problems with the mouse pointer and interferes with normal use, and if reverting to the normal driver does not allow image generation at all, then this software is useless.
Can't you get it to work with regular Radeon Software?

Spec:
OS:Windows11 22H2
Videocard:AMD Radeon RX 6750 XT
Python:3.10.9

**Comment by qwerkilo** [comment]
i use this driver and work fine.https://sourceforge.net/projects/amernimezone/files ver23.1.1

**Comment by powderluv** [comment]
Hopefully in a few weeks you can use the regular drivers.

**Comment by steyRNG** [comment]
Also useful link for those kinda special versions of drivers: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-vulkan

**Comment by excelsior091224** [comment]
> Heya, new Version dropped for 7900 Series, 23.1.2 added Support for "IREE compiler using MLIR interface on Vulkan."
> 
> Shouldn't be long til the drop for the other Series. https://www.amd.com/de/support/kb/release-notes/rn-rad-win-23-1-2-kb

It's been 3 weeks and not a single driver for the 6000 series or earlier has been released.
This is going to cause another exodus of customers to Nvidia.

**Comment by powderluv** [comment]
As of yesterday the regular AMD driver can be used for SHARK https://www.amd.com/en/support/kb/release-notes/rn-rad-win-23-2-1 . Please try it and report any issues with it. Closing this issue out.
