### ISSUE TITLE
Missing dependencies when converting ckpt files

### ISSUE THREAD

**Issue by drumicube** [nod-ai/SHARK#878]
As explained in this [README](https://github.com/nod-ai/SHARK/tree/main/shark/examples/shark_inference/stable_diffusion#run-a-custom-model-using-a-huggingface-ckpt-file) the custom model converter needs 3 additional dependencies:

`
pip install omegaconf safetensors pytorch_lightning
`

Each time I clear the venv, I have to manually reinstall them, this could also be confusing for newcomers.
More over, don't we risk to miss them in executable release bundles ?
Knowing than most users will convert ckpt files, wouldn't it be more practical to add them in the default requirements ?

Thanks.

**Comment by Abhishek-Varma** [comment]
Hi @drumicube,

Thanks for raising this issue! We agree this was an overkill and have now addressed that with one exception -> `pytorch-lightning` is needed only for a few HuggingFace models' `.ckpt` files as metioned [here](https://github.com/nod-ai/SHARK/blob/main/shark/examples/shark_inference/stable_diffusion/README.md#run-a-custom-model-using-a-huggingface-ckpt-file).

@powderluv

**Comment by drumicube** [comment]
Thank you !

**Comment by powderluv** [comment]
added most of them. I still wan't to try and avoid pytorch-lightning because of one model.
