### ISSUE TITLE
No module named 'shark'

### ISSUE THREAD

**Issue by mvre** [nod-ai/SHARK#884]
After trying to run the command "python index.py", it gives me ModuleNotFoundError and I don't know how to fix this

Here I paste the output of the command
PS D:\stable_diffusion\SHARK\web> python .\index.py
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\stable_diffusion\SHARK\web\index.py", line 14, in <module>
    from models.stable_diffusion.main import stable_diff_inf
  File "D:\stable_diffusion\SHARK\web\models\stable_diffusion\main.py", line 5, in <module>
    from models.stable_diffusion.cache_objects import model_cache
  File "D:\stable_diffusion\SHARK\web\models\stable_diffusion\cache_objects.py", line 10, in <module>
    from models.stable_diffusion.opt_params import get_unet, get_vae, get_clip
  File "D:\stable_diffusion\SHARK\web\models\stable_diffusion\opt_params.py", line 2, in <module>
    from models.stable_diffusion.model_wrappers import (
  File "D:\stable_diffusion\SHARK\web\models\stable_diffusion\model_wrappers.py", line 3, in <module>
    from models.stable_diffusion.utils import compile_through_fx
  File "D:\stable_diffusion\SHARK\web\models\stable_diffusion\utils.py", line 3, in <module>
    from shark.shark_inference import SharkInference
ModuleNotFoundError: No module named 'shark'

This happens when I try to run stable diffusion in command line too. Same error

EDIT: I saw that there is the same closed issue on steam deck. I'm not on steam deck

**Comment by xzuyn** [comment]
are you in the virtual environment? before you run shark you need to enter the venv. open the command line in the `SHARK` directory then type `shark.venv/scripts/activate`. you can then move to the `web` directory with `cd web`

that will make your command line look like `(shark.venv) D:\stable_diffusion\SHARK\web>`.

once you've done that you should be able to run the program the same way you tried using `python .\index.py`

**Comment by GhostofXavier** [comment]
Did you change any of the folder structure? I had this exact same issue yesterday when I was forced to remove a space in the folder structure (i.e. G:\stable diffusion\shark\*files*\ to G:\stablediffusion\shark\*files*\) for an unrelated reason. I think there is an absolute reference somewhere in the code where it should be a relative reference and it breaks things.

My fix was to blow away the shark folder and start from scratch. I'm fortunate enough to have a good enough internet connection that it isn't too inconvenient.
