### ISSUE TITLE
Model Error - baked in VAE? Safetensor?

### ISSUE THREAD

**Issue by samsismas** [nod-ai/SHARK#921]
The huggingface ID on exe WebUI v483 fails to convert: _GalaxyTimeMachine/GTM_UltimateBlend_v3_
https://huggingface.co/GalaxyTimeMachine/GTM_UltimateBlend_v3

This model is popular on civitai with >6300 downloads, but the same username/model name on huggingface has zero downloads, however the username is the same, and links to the same patreon site on HF and civitAI: https://civitai.com/models/4884/galaxytimemachines-gtmultimateblendv3

**Comment by powderluv** [comment]
please test with the latest build. it works.
