### ISSUE TITLE
Suboptimal caching/vmfb loading

### ISSUE THREAD

**Issue by dan-garvey** [nod-ai/SHARK#923]
Currently when using the flag --load_vmfb, several GB of artifacts are still downloaded from the shark tank, even if a vmfb is detected and no redownload is required.

**Comment by gavbaa** [comment]
I can confirm this issue on Windows 10 as well (original poster appears to be Linux).

**Comment by dan-garvey** [comment]
Solved by adding the correct hash to the shark tank dir
