### ISSUE TITLE
json and png chunk data has incorrect variant listed

### ISSUE THREAD

**Issue by samsismas** [nod-ai/SHARK#942]
json and png chunk data has incorrect variant when a local model is used in the webUI (490) in the "Place all checkpoints in models/" drop-down box.

**Comment by powderluv** [comment]
@EvanGuanSF (original author) fyi in case you want to fix. If not we can add it to our list.

**Comment by powderluv** [comment]
should be fixed [now](https://github.com/nod-ai/SHARK/pull/962). Please reopen if you have any issues.
