### ISSUE TITLE
Shark build 496 497 is generating duplicate images between two folders

### ISSUE THREAD

**Issue by Zengrath** [nod-ai/SHARK#956]
Shark build 496 or 497 is generating duplicate images between two folders

\shark_tmp

\generated_imgs

duplicates are not being made in the C:\Users\username\AppData\Local\Temp directory any longer with build 496 and 497 in my current testing.

**Comment by monorimet** [comment]
Thanks for sharing this. I'll put up a fix ASAP.

**Comment by Zengrath** [comment]
An update on this as of build 506. I'm currently seeing images duplicated between the \generated_imgs folder as well as the shark main directory now.

in main directory I'm seeing all the images dupilicated as  tmpbys8lfqk.png tmpcv_8bcwg.png etc. and are same images in my generated_imgs folder. I am not currently seeing dups in my temp folder or the shark_tmp folder.

**Comment by monorimet** [comment]
Ok-- thanks for updating. I'll check it out tomorrow morning.

**Comment by monorimet** [comment]
Looks like gradio creates a copy of the generated image that they can mess with to fit in the web UI.
They work on the tmp_something.png as to not modify the original image.

I'll look into having these cleaned up properly when they are no longer needed.
