### ISSUE TITLE
Not able to run custom model and index.py in powershell

### ISSUE THREAD

**Issue by MVR3S** [nod-ai/SHARK#957]
When I try to generate an image using a custom model it gives me an error and in the visual studio terminal it gives me this output:

Diffusers' checkpoint will be identified here :  D:/stable_diffusion/custom/SHARK/models/rpg_V3Candidate16
Loading diffusers' pipeline from original stable diffusion checkpoint
global_step key not found in model
'wget' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
...
and after the list of the most recent call there is the following error
...
  File "d:\stable_diffusion\custom\SHARK\shark.venv\lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\stable_diffusion\\custom\\SHARK\\shark_tmp\\tmptks2ri76\\inferenc.yaml'

I have no idea how to fix this issue. I also can't run index.py from the powershell because it gives the error:
Traceback (most recent call last):
  File "D:\stable_diffusion\custom\SHARK\apps\stable_diffusion\web\index.py", line 23, in <module>
    from apps.stable_diffusion.src import (
ModuleNotFoundError: No module named 'apps'

(Im using shark.venv but the first time I executed index.py it worked)

**Comment by powderluv** [comment]
You need to download and place wget in your path until diffusers is updated. Please see the FAQ in discord too.
