### ISSUE TITLE
-1 value in seed for randomizing, is making all outputs have -1 seed value

### ISSUE THREAD

**Issue by vicioustide** [nod-ai/SHARK#964]
On builds before Shark#475, they had the correctly working feature of entering "-1" for randomizing seed generator that would generate an image with a random seed value in the images information panel which then could be useful for re-prompting the image. Now all builds after #475, when "-1" is entered for randomizing seed, only "-1" shows up in every generated images seed value, which is not useful at all for knowing what the true seed value is for re-prompting the image.
<img width="951" alt="Issue" src="https://user-images.githubusercontent.com/123191281/217113601-741fc1fb-9156-4179-9486-bfcf4ce9a963.PNG">

**Comment by powderluv** [comment]
Can you please try with 501? It should be fixed now.

**Comment by vicioustide** [comment]
> Can you please try with 501? It should be fixed now.

It works! Thank you very much! Much better!
